# Generated by Django 2.2.14 on 2020-07-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='user',
            new_name='author',
        ),
    ]
