# Generated by Django 2.2.14 on 2020-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200719_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
