# Generated by Django 2.2.14 on 2020-07-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_contents_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
